.TH "md__r_e_a_d_m_e" 3 "Sun Apr 26 2020" "Max-mean dispersion problem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Arbol de directorios 

.PP
.nf
\&.
├── build
│   ├── Makefile
│   └── main
├── ejemplos
│   ├── max-mean-div-10\&.txt        
│   ├── max-mean-div-15\&.txt        
│   └── max-mean-div-20\&.txt        
├── include
│   ├── algorithm\&.hpp
│   ├── exec\&.hpp
│   ├── file\&.hpp
│   ├── graph\&.hpp
│   ├── grasp-algorithm\&.hpp        
│   ├── greedy-algorithm\&.hpp       
│   ├── second-greedy-algorithm\&.hpp
│   └── solution\&.hpp
└── src
    ├── algorithm\&.cpp
    ├── algorithm\&.o
    ├── exec\&.cpp
    ├── exec\&.o
    ├── file\&.cpp
    ├── file\&.o
    ├── graph\&.cpp
    ├── graph\&.o
    ├── grasp-algorithm\&.cpp
    ├── grasp-algorithm\&.o
    ├── greedy-algorithm\&.cpp
    ├── greedy-algorithm\&.o
    ├── main\&.cpp
    ├── main\&.o
    ├── second-greedy-algorithm\&.cpp
    ├── second-greedy-algorithm\&.o
    ├── solution\&.cpp
    └── solution\&.o

.fi
.PP
 
