.TH "SecondGreedyAlgorithm" 3 "Sun Apr 26 2020" "Max-mean dispersion problem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecondGreedyAlgorithm \- Esta clase representa el segundo algoritmo constructivo voraz del cual la idea ha sido partir de una lista con todo el conjunto de nodos e ir eliminando de la misma\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <second\-greedy\-algorithm\&.hpp>\fP
.PP
Inherits \fBAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecondGreedyAlgorithm\fP (std::string newName)"
.br
.RI "Construye la variante del algoritmo greedy con un nombre\&. "
.ti -1c
.RI "\fBSolution\fP \fBrun\fP (\fBGraph\fP currentGraph)"
.br
.RI "Representa la variante del algoritmo voraz que consiste en partir de un vector que está lleno de todos los elementos y en vez de ir añadiendo, en este caso se van eliminando\&. "
.ti -1c
.RI "std::string \fBgetAlgorithmName\fP ()"
.br
.RI "Devuelve el nombre del algoritmo\&. "
.in -1c
.SH "Detailed Description"
.PP 
Esta clase representa el segundo algoritmo constructivo voraz del cual la idea ha sido partir de una lista con todo el conjunto de nodos e ir eliminando de la misma\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecondGreedyAlgorithm::SecondGreedyAlgorithm (std::string newName)"

.PP
Construye la variante del algoritmo greedy con un nombre\&. 
.PP
\fBParameters\fP
.RS 4
\fInewName\fP Nombre del algoritmo 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string SecondGreedyAlgorithm::getAlgorithmName ()"

.PP
Devuelve el nombre del algoritmo\&. 
.PP
\fBReturns\fP
.RS 4
std::string nombre del algoritmo 
.RE
.PP

.SS "\fBSolution\fP SecondGreedyAlgorithm::run (\fBGraph\fP currentGraph)\fC [virtual]\fP"

.PP
Representa la variante del algoritmo voraz que consiste en partir de un vector que está lleno de todos los elementos y en vez de ir añadiendo, en este caso se van eliminando\&. En el caso de la solución se pasa un 2 para indicar que en las búsquedas greedy no hay distinción de búsqueda local greedy o ansiosa\&.
.PP
\fBParameters\fP
.RS 4
\fIcurrentGraph\fP Representa el grafo actual 
.RE
.PP
\fBReturns\fP
.RS 4
std::vector <int> Representa la solución 
.RE
.PP

.PP
Implements \fBAlgorithm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max-mean dispersion problem from the source code\&.
