.TH "Solution" 3 "Sun Apr 26 2020" "Max-mean dispersion problem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Solution \- Representa una solucion, que va a contener el vector donde se almacena la misma , la media y luego el tiempomque ha tardado en hallarla\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <solution\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolution\fP (std::vector< int > currentSolution, float currentMedia, std::string newAlgorithmName, int localSearch)"
.br
.RI "Construye la solución, a partir de un vector, un valor y un nombre de un algoritmo\&. "
.ti -1c
.RI "float \fBgetMedia\fP ()"
.br
.RI "Devuelve el valor de la media de dispersión\&. "
.ti -1c
.RI "std::vector< int > \fBgetSolution\fP ()"
.br
.RI "Devuelve el vector de solución\&. "
.ti -1c
.RI "int \fBgetRunTime\fP ()"
.br
.RI "Devuelve el tiempo de ejecución\&. "
.ti -1c
.RI "void \fBsetRunTime\fP (int newRunTime)"
.br
.RI "Modifica el valor de tiempo de ejecución\&. "
.ti -1c
.RI "std::string \fBgetAlgorithmName\fP ()"
.br
.RI "Devuelve el nombre del algoritmo de la solución\&. "
.ti -1c
.RI "int \fBgetSolutionValue\fP (int position)"
.br
.RI "Devuelve el valor de la solución en la posición que se haya obtenido por parámetro\&. "
.ti -1c
.RI "int \fBgetLocalSearch\fP ()"
.br
.RI "Devuelve un 0 si la búsqueda local es ansiosa y un 1 si la búsqueda local es greedy\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBSolution\fP currentSolution)"
.br
.RI "Representa la sobrecarga del operador <<, que va a hacer la impresión de la solución\&. "
.in -1c
.SH "Detailed Description"
.PP 
Representa una solucion, que va a contener el vector donde se almacena la misma , la media y luego el tiempomque ha tardado en hallarla\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Solution::Solution (std::vector< int > currentSolution, float currentMedia, std::string newAlgorithmName, int newLocalSearch)"

.PP
Construye la solución, a partir de un vector, un valor y un nombre de un algoritmo\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrentSolution\fP Representa el vector que contiene la solución 
.br
\fIcurrentMedia\fP Representa el valor de la media de dispersión de la solución 
.br
\fInewAlgorithmName\fP Representa el nombre del algoritmo 
.br
\fInewLocalSearch\fP Representa la búsqueda local usada por el algoritmo 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string Solution::getAlgorithmName ()"

.PP
Devuelve el nombre del algoritmo de la solución\&. 
.PP
\fBReturns\fP
.RS 4
std::string Valor del nombre del nombre del algoritmo 
.RE
.PP

.SS "int Solution::getLocalSearch ()"

.PP
Devuelve un 0 si la búsqueda local es ansiosa y un 1 si la búsqueda local es greedy\&. 
.PP
\fBReturns\fP
.RS 4
int Valor de la búsqueda 
.RE
.PP

.SS "float Solution::getMedia ()"

.PP
Devuelve el valor de la media de dispersión\&. 
.PP
\fBReturns\fP
.RS 4
float Valor de la media de dispersión 
.RE
.PP

.SS "int Solution::getRunTime ()"

.PP
Devuelve el tiempo de ejecución\&. 
.PP
\fBReturns\fP
.RS 4
int Valor del tiempo de ejecución 
.RE
.PP

.SS "std::vector< int > Solution::getSolution ()"

.PP
Devuelve el vector de solución\&. 
.PP
\fBReturns\fP
.RS 4
std::vector <int> Vector de solución 
.RE
.PP

.SS "int Solution::getSolutionValue (int position)"

.PP
Devuelve el valor de la solución en la posición que se haya obtenido por parámetro\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP Posición a buscar en el vector 
.RE
.PP
\fBReturns\fP
.RS 4
int Valor en la posición del vector 
.RE
.PP

.SS "void Solution::setRunTime (int newRunTime)"

.PP
Modifica el valor de tiempo de ejecución\&. 
.PP
\fBParameters\fP
.RS 4
\fInewRunTime\fP Nuevo tiempo de ejecución 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, \fBSolution\fP currentSolution)\fC [friend]\fP"

.PP
Representa la sobrecarga del operador <<, que va a hacer la impresión de la solución\&. 
.PP
\fBParameters\fP
.RS 4
\fIos\fP Ostream para imprimir 
.br
\fIcurrentSolution\fP Solución que se va aimprimir 
.RE
.PP
\fBReturns\fP
.RS 4
std::ostream& valor de impresión 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Max-mean dispersion problem from the source code\&.
